### ISSUE TITLE
Licensing of `Source/leathers/narrowing`

### ISSUE THREAD

**Issue by merkys** [ruslo/leathers#14]
File `Source/leathers/narrowing` contains the following copyright statement:
https://github.com/ruslo/leathers/blob/0a9103d18b412a7dd5ead63bd175a8d5c1094d75/Source/leathers/narrowing#L1

Just to clarify, this does not affect the overall BSD-2-clause licensing, right?

**Comment by ruslo** [comment]
> File Source/leathers/narrowing contains the following copyright statement

That's just a specific contribution, the license in the top-level directory is applied for all the files:
- https://github.com/ruslo/leathers/blob/0a9103d18b412a7dd5ead63bd175a8d5c1094d75/LICENSE

**Comment by merkys** [comment]
Thanks for confirming @ruslo
